### ISSUE TITLE
i made something similar

### ISSUE THREAD

**Issue by paulirish** [kevva/github-user-email#1]
heh. apparently it was the time of year for this project. :)

https://github.com/paulirish/github-email

well its based off sindre's original gist, but.. you'll see.

**Comment by paulirish** [comment]
I use a few different techniques since the API rarely has the answer.

**Comment by kevva** [comment]
Hah, yeah, I saw. Just wanted something using a JS API to add to my [collection](https://github.com/search?q=user%3Akevva+github-), lol.

**Comment by paulirish** [comment]
ah very nice. ;)
